# Generated by Django 2.2.4 on 2020-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator', '0006_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name_text',
            field=models.CharField(default='defaultname', max_length=100),
        ),
    ]
