# Generated by Django 2.2.4 on 2020-08-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator', '0007_auto_20200804_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ip_address',
            field=models.CharField(default="IP dosen't exist", max_length=100),
        ),
    ]
