# Generated by Django 2.2.4 on 2020-08-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator', '0008_search_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='is_correct',
            field=models.CharField(default='-1', max_length=100),
        ),
    ]
